### ISSUE TITLE
Support refresh tokens

### ISSUE THREAD

**Issue by jwoudenberg** [lehins/wai-middleware-auth#12]
I'm curious if there's an interest to add support for refresh tokens to the oauth2 middleware. If there is I'd be happy to work on a PR to add this support.

Some OAuth2 providers will as part of the authorization flow return a refresh token. When an access token or idtoken expires the refresh token can be used to obtain new tokens. These new tokens might also contain a new refresh token. The following link describes the use of refresh tokens in more detail:

https://auth0.com/learn/refresh-tokens/

An application which would like to make use of the refresh token flow currently has a problem. It has access to the refresh token and could make a request for new tokens, but once this has been completed it doesn't have the possibility to write these newly retrieved tokens back to the session. The next request will not be able to use them.

The change I'd like to propose is that the middleware checks the expiry date of the accesstoken, and also of the idtoken if one exists. If either is expired one of two things happens:

- If a refresh token is available it is used to retrieve a new access token (and optionally id token). These replace the old tokens in the session.
- If no refresh token is available the session gets invalidated and a new authorization flow is started.

I'd love to hear your thoughts on this proposal!

**Comment by lehins** [comment]
I think refresh tokens is a good feature to have. I thought about implementing it when I was working initially on the library, but it wasn't critical for us, so I decided to postpone it to better times. If you'd like to work on this feature I'll be happy to merge such PR. Your overall plan on how to tackle the problem seems right to me.
