### ISSUE TITLE
Delete session if OAuth2 access token is no longer valid

### ISSUE THREAD

**Issue by jwoudenberg** [lehins/wai-middleware-auth#8]
I'm wondering how to best deal with the following scenario:

- User visits site, is not logged in and goes through the OAuth2 login flow.
- User now has a session containing an OAuth2 access token.
- Time passes.
- User visits site again. The middleware passes the user through on account of the session still being valid, but when the site uses the access token from the session to make an OAuth2-protected request it founds out the access token is no longer valid.

At this point I think the session is effectively dead, and the session cookie should be destroyed so the user can go through the authentication flow again. There's a couple of ways this might happen:

1. The application could destroy the cookie itself (this is what I do currently). Downside: it needs to know the exact cookie name and path to do so, which is tied to the implementation of `wai-middleware-auth`.
1. The middleware could expose a helper function for generating the header required to delete the cookie. That keeps the knowledge for dealing with the cookie within this package.
1. The application sends a 401 error response, and the middleware picks up on this and adds a header on the response deleting the session cookie.

I particularly like the last option because it keeps all session management concerns on the layer of the middleware. On the other hand the behavior might be too magical. Maybe it could be an option?

I'd love your thoughts. If there's an interest I might follow up with a PR.

**Comment by lehins** [comment]
I'm leaning towards the second option, which will be the best compromise, I think. This would allow a user to cleanup the cookie easier. Note that the cookie name is customizable with `setAuthCookieName` while default one being `"auth_state"`. The path is hardcoded to `"/"`.
The 3rd option is not only magical, but can have a surprising side effect. For instance application sends 401, cause it has some other extra authentication mechanism that has failed, this would in turn invalidate oauth2. Somewhat unlikely scenario, but nevertheless not an impossible one, therefore I'd like to avoid it.

**Comment by jwoudenberg** [comment]
Makes sense! I'll create a PR for the function described by option 2.
